### ISSUE TITLE
a question about human size and 3D position

### ISSUE THREAD

**Issue by Kongbaikb** [FrozenBurning/PrimDiffusion#1]
Thank you for your outstanding work! May I ask if it is possible to change the size of the human body and its position in 3D space during inference?

**Comment by FrozenBurning** [comment]
Thanks for your interest in our work! Of course, you can change the size and 3D position of the human body. At inference time, you can change the `shape` parameter [here](https://github.com/FrozenBurning/PrimDiffusion/blob/76d82f7b89a268e5871cbbb0561d81194b47160f/visualize.py#L139) to control the size of the human body and apply global translation to the decoded `geom` to change the position.

**Comment by FrozenBurning** [comment]
Close due to inactivity. Feel free to reopen for further questions!
